routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.'], function() {

        Route::get('/clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');


        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        Route::get('/', 'Admin\AdminController@dashboard')->name('dashboard');

        Route::get('forgot_password','Auth\AdminLoginController@showLinkRequestForm')->name('forgot_password.request');

        Route::post('forgot_password_update', 'Auth\AdminLoginController@forgot_password_update')->name('forgot_password.update');

        // Users CRUD Operations

        Route::get('users', 'Admin\AdminUserController@users_index')->name('users.index');

        Route::get('users/create', 'Admin\AdminUserController@users_create')->name('users.create');

        Route::get('users/edit', 'Admin\AdminUserController@users_edit')->name('users.edit');

        Route::post('users/save', 'Admin\AdminUserController@users_save')->name('users.save');

        Route::get('users/view', 'Admin\AdminUserController@users_view')->name('users.view');

        Route::get('users/delete', 'Admin\AdminUserController@users_delete')->name('users.delete');

        Route::get('users/status', 'Admin\AdminUserController@users_status')->name('users.status');

        Route::get('users/excel','Admin\AdminUserController@users_excel')->name('users.excel');

        Route::get('users/verify', 'Admin\AdminUserController@users_verify_status')->name('users.verify');

        Route::get('users/export/','Admin\AdminUserController@users_export')->name('users.export');

        Route::get('minted_contracts', 'Admin\AdminUserController@minted_contracts')->name('minted_contracts');
        
        Route::get('invested_projects', 'Admin\AdminUserController@invested_projects')->name('invested_projects');

        Route::get('invested_projects/view', 'Admin\AdminUserController@invested_projects_view')->name('invested_projects.view');

        Route::get('invested_projects/claim', 'Admin\AdminUserController@invested_projects_claim')->name('invested_projects.claim');
        
        Route::post('/users/bulk_action', 'Admin\AdminUserController@users_bulk_action')->name('users.bulk_action');

        Route::get('/users/staked_amount', 'Admin\AdminUserController@users_staked_amount')->name('users.staked_amount');

        
        Route::post('subscriptions/bulk_action', 'Admin\SubscriptionController@subscriptions_bulk_action')->name('subscriptions.bulk_action');


        Route::get('profile', 'Admin\AdminAccountController@profile')->name('profile');

        Route::post('profile/save', 'Admin\AdminAccountController@profile_save')->name('profile.save');

        Route::post('change/password', 'Admin\AdminAccountController@change_password')->name('change.password');
        
        Route::get('transactions/getaccount', 'Admin\BlockOperationController@transactions_getaccount')->name('transactions.getaccount');

        Route::post('transactions/history', 'Admin\BlockOperationController@transactions_index')->name('transactions.index');

        Route::get('wallets/view', 'Admin\BlockOperationController@transactions_getaccount')->name('wallets.view');

        // settings

        Route::get('control', 'Admin\AdminSettingController@settings_control')->name('settings-control'); 

        Route::get('settings', 'Admin\AdminSettingController@settings')->name('settings'); 

        Route::post('settings/save', 'Admin\AdminSettingController@settings_save')->name('settings.save'); 

        Route::post('env_settings','Admin\AdminSettingController@env_settings_save')->name('env-settings.save');

        // Documents CRUD operations

        Route::get('documents/index', 'Admin\AdminLookupController@documents_index')->name('documents.index');

        Route::get('documents/create', 'Admin\AdminLookupController@documents_create')->name('documents.create');
 
        Route::get('documents/edit', 'Admin\AdminLookupController@documents_edit')->name('documents.edit');
 
        Route::post('documents/save', 'Admin\AdminLookupController@documents_save')->name('documents.save');
 
        Route::get('documents/view', 'Admin\AdminLookupController@documents_view')->name('documents.view');
 
        Route::get('documents/delete', 'Admin\AdminLookupController@documents_delete')->name('documents.delete');
 
        Route::get('documents/status', 'Admin\AdminLookupController@documents_status')->name('documents.status');
 
        //user documents 

        Route::get('user-documents', 'Admin\AdminUserController@user_documents_index')->name('user_documents.index');

        Route::get('user-document', 'Admin\AdminUserController@user_documents_view')->name('user_documents.view');

        Route::get('user-documents/verify', 'Admin\AdminUserController@user_documents_verify')->name('user_documents.verify');

        // STATIC PAGES

        Route::get('static_pages' , 'Admin\AdminLookupController@static_pages_index')->name('static_pages.index');

        Route::get('static_pages/create', 'Admin\AdminLookupController@static_pages_create')->name('static_pages.create');

        Route::get('static_pages/edit', 'Admin\AdminLookupController@static_pages_edit')->name('static_pages.edit');

        Route::post('static_pages/save', 'Admin\AdminLookupController@static_pages_save')->name('static_pages.save');

        Route::get('static_pages/delete', 'Admin\AdminLookupController@static_pages_delete')->name('static_pages.delete');

        Route::get('static_pages/view', 'Admin\AdminLookupController@static_pages_view')->name('static_pages.view');

        Route::get('static_pages/status', 'Admin\AdminLookupController@static_pages_status_change')->name('static_pages.status');

        //faq CRUD
        Route::get('faqs', 'Admin\AdminLookupController@faqs_index')->name('faqs.index');

        Route::get('faqs/create', 'Admin\AdminLookupController@faqs_create')->name('faqs.create');

        Route::get('faqs/edit', 'Admin\AdminLookupController@faqs_edit')->name('faqs.edit');

        Route::post('faqs/save', 'Admin\AdminLookupController@faqs_save')->name('faqs.save');

        Route::get('faqs/view', 'Admin\AdminLookupController@faqs_view')->name('faqs.view');

        Route::get('faqs/delete', 'Admin\AdminLookupController@faqs_delete')->name('faqs.delete');

        Route::get('faqs/status', 'Admin\AdminLookupController@faqs_status')->name('faqs.status');
        //faq end

        Route::get('projects', 'Admin\AdminProjectController@projects_index')->name('projects.index');

        Route::get('projects/create', 'Admin\AdminProjectController@projects_create')->name('projects.create');

        Route::get('projects/edit', 'Admin\AdminProjectController@projects_edit')->name('projects.edit');

        Route::post('projects/save', 'Admin\AdminProjectController@projects_save')->name('projects.save');

        Route::get('projects/view', 'Admin\AdminProjectController@projects_view')->name('projects.view');

        Route::get('projects/delete', 'Admin\AdminProjectController@projects_delete')->name('projects.delete');

        Route::get('projects/status', 'Admin\AdminProjectController@projects_status')->name('projects.status');

        Route::get('projects/publish_status', 'Admin\AdminProjectController@projects_publish_status')->name('projects.publish_status');

        // Subscriptions
        
        Route::get('subscriptions', 'Admin\SubscriptionController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'Admin\SubscriptionController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'Admin\SubscriptionController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'Admin\SubscriptionController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'Admin\SubscriptionController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'Admin\SubscriptionController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'Admin\SubscriptionController@subscriptions_status')->name('subscriptions.status');

        // Subscription Payments

        Route::get('subscription_payments/index','Admin\SubscriptionController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','Admin\SubscriptionController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenues/dashboard','Admin\AdminRevenueController@revenues_dashboard')->name('revenues.dashboard');

        // Project Payments

        Route::get('project_payments/index','Admin\AdminProjectController@project_payments_index')->name('project_payments.index');

        Route::get('project_payments/view','Admin\AdminProjectController@project_payments_view')->name('project_payments.view');


        Route::get('token_payments/index','Admin\AdminRevenueController@token_payments_index')->name('token_payments.index');

        Route::get('token_payments/view','Admin\AdminRevenueController@token_payments_view')->name('token_payments.view');


        Route::get('project-view','Admin\AdminProjectController@projects_view_for_web')->name('projects_view_for_web');

        // Ajax Functions


        Route::post('projects/pool_contract_save','Admin\AdminProjectController@projects_pool_contract_save')->name('projects_pool_contract_save');

        Route::post('projects_burn_access_update','Admin\AdminProjectController@projects_burn_access_update')->name('projects_burn_access_update');

routes/web.php
<?php

use  App\Http\Controllers\UserAuthController;

use  App\Http\Controllers\AdminAuthController;

use  App\Http\Controllers\ReactController;

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::view('/{path?}', 'app');

// Route::get('/{path?}', [
//     'uses' => 'ReactController@show',
//     'as' => 'react',
//     'where' => ['path' => 'burn|mint|new']
// ]);

// Route::get('/project/{path?}', function () {
//     return view('app');
// })->where('path', '.*');

// 
// // Route::get('/{url?}', function () {
//     return view('app');
// })->where('', 'list');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/test', function(){
    return view('test');
});

// User

Route::get('/', [UserAuthController::class, 'index'])->name('user.home') ->middleware('auth:web');

Route::get('/login', [UserAuthController::class, 'login'])->name('user.login');

Route::post('/login', [UserAuthController::class, 'handleLogin'])->name('user.handleLogin');

Route::get('/logout', [UserAuthController::class, 'index'])->name('user.logout');

Route::get('email', 'SampleController@email_check');

resources/views/admin/account/profile-new.blade.php
@extends('layouts.admin') 

@section('title', tr('profile')) 

@section('content-header', tr('profile')) 

@section('breadcrumb')

<li class="breadcrumb-item active">{{tr('profile')}}</li>

@endsection 

@section('content')

<div class="row">
    <div class="col-xl-4 col-lg-5">
        <!-- Profile Image -->
        <div class="box">
            <div class="box-body box-profile">
                
                <img class="profile-user-img rounded-circle img-fluid mx-auto d-block" src="{{Auth::guard('admin')->user()->picture}}" alt="{{Auth::guard('admin')->user()->name}}">
                
                <h3 class="profile-username text-center">{{Auth::guard('admin')->user()->name}}</h3>
                
                <p class="text-muted text-center">{{Auth::guard('admin')->user()->email}}</p>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
    <div class="col-xl-8 col-lg-7">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                
                <li><a class="active" href="#update_profile" data-toggle="tab">{{tr('update_profile')}}</a></li>
                
                <li><a id="base-tab_upload_image" data-toggle="tab" aria-controls="tab_upload_image" href="#tab_upload_image" aria-expanded="false">{{tr('upload_image')}}</a></li>
                
                <li><a href="#tab_change_password" id="base-tab_change_password"  data-toggle="tab" aria-controls="tab_change_password" href="#tab_change_password" aria-expanded="false">{{tr('change_password')}}</a></li>
            </ul>
            <div class="tab-content">
                <div class="active tab-pane" id="update_profile">
                    <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.profile.save') }}" method="POST" enctype="multipart/form-data" role="form">
                        @csrf

                        <input type="hidden" name="admin_id" value="{{Auth::guard('admin')->user()->id}}">

                        <div class="form-group">
                            <label for="name" required class="col-sm-2 control-label">{{ tr('name') }}</label>

                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="name" name="name" value="{{ Auth::guard('admin')->user()->name }}" placeholder="{{ tr('username') }}" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="email" class="col-sm-2 control-label">{{ tr('email') }}</label>

                            <div class="col-sm-10">
                                <input type="email" required value="{{ Auth::guard('admin')->user()->email }}" name="email" class="form-control" id="email" placeholder="{{ tr('email') }}">
                            </div>
                        </div>

                        <!-- <div class="form-group">
                            <label for="about" class="col-sm-2 control-label">{{ tr('about') }}</label>

                            <div class="col-sm-10">
                                <input type="text" value="{{ Auth::guard('admin')->user()->about }}" name="about" class="form-control" id=" " placeholder="{{ tr('about') }}">
                               
                            </div>
                        </div> -->

                        <div class="form-actions padding-btm-zero">

                            <button type="reset" class="btn btn-warning mr-1">
                                <i class="ft-x mr-1"></i> {{ tr('reset') }} 
                            </button>

                            <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o mr-1"></i>{{ tr('submit') }}</button>
                            
                            <div class="clearfix"></div>

                        </div>

                    </form>
                </div>

                <!-- /.tab-pane -->
                <div class="tab-pane" id="tab_upload_image" aria-labelledby="base-tab_upload_image">
                    <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.profile.save') }}" method="POST" enctype="multipart/form-data" role="form">
                        @csrf

                         <input type="hidden" name="admin_id" value="{{Auth::guard('admin')->user()->id}}">

                        @if(Auth::guard('admin')->user()->picture)
                            <img style="height: 90px; margin-bottom: 15px; border-radius:2em;" src="{{ Auth::guard('admin')->user()->picture }}"> 
                        @else
                            <img style="height: 90px; margin-bottom: 15px; border-radius:2em;" class="profile-user-img img-responsive img-circle" src="{{ asset('placeholder.jpeg') }}">
                         @endif

                        <div class="form-group">
                            <label for="picture" class="col-sm-2 control-label">{{ tr('picture') }}</label>

                            <div class="col-sm-10">
                                <input type="file" required accept="image/png,image/jpeg" name="picture" id="picture">
                                <p class="help-block">{{ tr('image_validate') }}</p>
                            </div>
                        </div>

                        <div class="form-actions">

                            <button type="reset" class="btn btn-warning mr-1">
                                <i class="ft-x"></i> {{ tr('reset') }} 
                            </button>

                            <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o"></i>{{ tr('submit') }}</button>
                            
                            <div class="clearfix"></div>

                        </div>

                    </form>
                </div>
                <!-- /.tab-pane -->

                <div class="tab-pane" id="tab_change_password" aria-labelledby="base-tab_change_password">

                    <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.change.password') }}" method="POST" enctype="multipart/form-data" role="form">
                        @csrf

                        <input type="hidden" name="admin_id" value="{{ Auth::guard('admin')->user()->id }}">

                        <div class="form-group">
                            <label for="old_password" class="col-sm-3 control-label">{{tr('old_password')}} *</label>

                            <div class="col-sm-8">
                                <input required type="password" class="form-control" name="old_password" id="old_password" placeholder="{{ tr('old_password') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="password" class="col-sm-3 control-label">{{tr('new_password')}} *</label>

                            <div class="col-sm-8">
                                <input required type="password" class="form-control" name="password" id="password" placeholder="{{ tr('new_password') }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="confirm_password" class="col-sm-3 control-label">{{tr('confirm_password')}} *</label>

                            <div class="col-sm-8">
                                <input type="password" required class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Enter {{tr('confirm_password')}}">
                            </div>
                        </div>

                        <div class="form-actions">

                            <button type="reset" class="btn btn-warning mr-1">
                                <i class="ft-x"></i> {{ tr('reset') }} 
                            </button>

                            <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o"></i>{{ tr('submit') }}</button>
                            
                            <div class="clearfix"></div>

                        </div>

                    </form>
                </div>
                <!-- /.tab-pane -->
            </div>
            <!-- /.tab-content -->
        </div>
        <!-- /.nav-tabs-custom -->
    </div>
    <!-- /.col -->

</div>

@endsection

resources/views/admin/account/profile.blade.php
@extends('layouts.admin') 

@section('title', tr('profile')) 

@section('content-header', tr('profile')) 

@section('breadcrumb')
<li class="breadcrumb-item active">{{tr('profile')}}</li>

@endsection 

@section('content')

<div id="user-profile">

    <div class="row">

        <div class="col-xl-4 col-lg-4 col-md-12">

            <div class="card">
                
                <div class="card-content">
                    
                    <div class="card-body">

                        <center class="m-t-30"> <img src="{{$admin->picture ?: asset('placeholder.jpeg')}}" class="img-circle mb-2" width="150" />

                            <h4 class="card-title m-t-10">{{$admin->name}}</h4>

                            <!-- <h6 class="card-subtitle">{{$admin->timezone}}</h6> -->
                        </center>



                        <ul class="list-group list-group-unbordered">

                            <li class="list-group-item">
                                <b>{{tr('email')}}</b> <a class="pull-right">{{$admin->email}}</a>
                            </li>
                            
                            <li class="list-group-item">
                                <b>{{tr('about')}}</b> <a class="pull-right">{{$admin->about}}</a>
                            </li>
                        </ul>
                    </div>

                </div>

            </div>

        </div>

        <div class="col-xl-8 col-lg-8 col-md-12">

            <div class="card">

                <div class="card-content">

                    <div class="card-body">
                   
                        <ul class="nav nav-tabs nav-top-border no-hover-bg reps-tab-flex">
                            <li class="nav-item">
                                <a class="nav-link active" id="base-tab_update_profile" data-toggle="tab" aria-controls="tab_update_profile" href="#tab_update_profile" aria-expanded="true">{{ tr('update_profile') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="base-tab_upload_image" data-toggle="tab" aria-controls="tab_upload_image" href="#tab_upload_image" aria-expanded="false">{{ tr('upload_image') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="base-tab_change_password" data-toggle="tab" aria-controls="tab_change_password" href="#tab_change_password" aria-expanded="false">{{ tr('change_password') }}</a>
                            </li>
                        </ul>

                        <div class="tab-content pt-1">

                            <div role="tabpanel" class="tab-pane active" id="tab_update_profile" aria-expanded="true" aria-labelledby="base-tab_update_profile">

                                <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.profile.save') }}" method="POST" enctype="multipart/form-data" role="form">
                                    @csrf

                                    <input type="hidden" name="admin_id" value="{{Auth::guard('admin')->user()->id}}">

                                    <div class="form-group">
                                        <label for="name" required class="col-sm-2 control-label">{{ tr('name') }}</label>

                                        <div class="col-sm-10">
                                            <input type="text" class="form-control" id="name" name="name" value="{{ Auth::guard('admin')->user()->name }}" placeholder="{{ tr('username') }}" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="email" class="col-sm-2 control-label">{{ tr('email') }}</label>

                                        <div class="col-sm-10">
                                            <input type="email" required value="{{ Auth::guard('admin')->user()->email }}" name="email" class="form-control" id="email" placeholder="{{ tr('email') }}">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="about" class="col-sm-2 control-label">{{ tr('about') }}</label>

                                        <div class="col-sm-10">
                                            <input type="text" value="{{ Auth::guard('admin')->user()->about }}" name="about" class="form-control" id=" " placeholder="{{ tr('about') }}">
                                           
                                        </div>
                                    </div>

                                    <div class="form-actions padding-btm-zero">

                                        <button type="reset" class="btn btn-warning mr-1">
                                            <i class="ft-x mr-1"></i> {{ tr('reset') }} 
                                        </button>

                                        <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o mr-1"></i>{{ tr('submit') }}</button>
                                        
                                        <div class="clearfix"></div>

                                    </div>

                                </form>

                            </div>

                            <div class="tab-pane" id="tab_upload_image" aria-labelledby="base-tab_upload_image">
                               
                                <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.profile.save') }}" method="POST" enctype="multipart/form-data" role="form">
                                    @csrf

                                     <input type="hidden" name="admin_id" value="{{Auth::guard('admin')->user()->id}}">

                                    @if(Auth::guard('admin')->user()->picture)
                                        <img style="height: 90px; margin-bottom: 15px; border-radius:2em;" src="{{ Auth::guard('admin')->user()->picture }}"> 
                                    @else
                                        <img style="height: 90px; margin-bottom: 15px; border-radius:2em;" class="profile-user-img img-responsive img-circle" src="{{ asset('placeholder.jpeg') }}">
                                     @endif

                                    <div class="form-group">
                                        <label for="picture" class="col-sm-2 control-label">{{ tr('picture') }}</label>

                                        <div class="col-sm-10">
                                            <input type="file" required accept="image/png,image/jpeg" name="picture" id="picture">
                                            <p class="help-block">{{ tr('image_validate') }}</p>
                                        </div>
                                    </div>

                                    <div class="form-actions">

                                        <button type="reset" class="btn btn-warning mr-1">
                                            <i class="ft-x"></i> {{ tr('reset') }} 
                                        </button>

                                        <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o"></i>{{ tr('submit') }}</button>
                                        
                                        <div class="clearfix"></div>

                                    </div>

                                </form>

                            </div>

                            <div class="tab-pane" id="tab_change_password" aria-labelledby="base-tab_change_password">

                                <form class="form-horizontal" action="{{ (Setting::get('is_demo_control_enabled') == YES) ? '#' : route('admin.change.password') }}" method="POST" enctype="multipart/form-data" role="form">
                                    @csrf

                                    <input type="hidden" name="admin_id" value="{{ Auth::guard('admin')->user()->id }}">

                                    <div class="form-group">
                                        <label for="old_password" class="col-sm-3 control-label">{{ tr('old_password') }}</label>

                                        <div class="col-sm-8">
                                            <input required type="password" class="form-control" name="old_password" id="old_password" placeholder="{{ tr('old_password') }}">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="password" class="col-sm-3 control-label">{{ tr('new_password') }}</label>

                                        <div class="col-sm-8">
                                            <input required type="password" class="form-control" name="password" id="password" placeholder="{{ tr('new_password') }}">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="confirm_password" class="col-sm-3 control-label">{{ tr('confirm_password') }}</label>

                                        <div class="col-sm-8">
                                            <input type="password" required class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Enter {{tr('confirm_password')}}">
                                        </div>
                                    </div>

                                    <div class="form-actions">

                                        <button type="reset" class="btn btn-warning mr-1">
                                            <i class="ft-x"></i> {{ tr('reset') }} 
                                        </button>

                                        <button type="submit" class="btn btn-primary" @if(Setting::get('is_demo_control_enabled') == YES) disabled @endif ><i class="fa fa-check-square-o"></i>{{ tr('submit') }}</button>
                                        
                                        <div class="clearfix"></div>

                                    </div>

                                </form>

                            </div>


                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>
    
</div>

@endsection 

@section('scripts')

<script>
    // input only number
    function isNumber(evt) {
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57) && charCode != 45) {
            return false;
        }
        return true;
    }
</script>

@endsection